apiVersion: v1
kind: Service
metadata:
    name: mashroom-portal
    namespace: default
    labels:
        app: mashroom-portal
spec:
    type: NodePort
    ports:
        -   port: 80
            targetPort: 5050
            nodePort: ${NODE_PORT_PORTAL}
    selector:
        app: mashroom-portal
