apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: keycloak-ingress
    namespace: default
    annotations:
        kubernetes.io/ingress.global-static-ip-name: keycloak-global-ip
spec:
    backend:
        serviceName: keycloak-http
        servicePort: 80
