apiVersion: v1
kind: Service
metadata:
    name: microfrontend-demo2
    namespace: default
    labels:
        app: microfrontend-demo2
spec:
    type: ClusterIP
    ports:
        -  port: 6089
           targetPort: 6089
    selector:
        app: microfrontend-demo2
