apiVersion: apps/v1
kind: Deployment
metadata:
    name: microfrontend-demo1
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: microfrontend-demo1
    template:
        metadata:
            labels:
                app: microfrontend-demo1
        spec:
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
            containers:
                -   name: mashroom-portal
                    image: k3d-${LOCAL_REGISTRY_NAME}:${LOCAL_REGISTRY_PORT}/microfrontend-demo1:latest
                    imagePullPolicy: Always
                    env:
                        -   name: NODE_ENV
                            value: production
                    resources:
                        requests:
                            cpu: 100m
                            memory: 80Mi
                    ports:
                        -   containerPort: 6088
                    readinessProbe:
                        httpGet:
                            path: /api/ready
                            port: 6088
                        initialDelaySeconds: 2
                        periodSeconds: 5
