apiVersion: v1
kind: Secret
metadata:
    name: platform-services
    namespace: ${COMMON_NAMESPACE}
type: Opaque
stringData:
    mongoDbUser: ${MONGODB_USER}
    mongoDbPassword: ${MONGODB_PASSWORD}
    keycloakClientId: ${KEYCLOAK_CLIENT_ID}
    keycloakClientSecret: ${KEYCLOAK_CLIENT_SECRET}
    redisPassword: ${REDIS_PASSWORD}
